method: tagfex

init_epochs: 200 # 200
inc_epochs: 170 # 170
eval_interval: 5


contrast_factor: 1
contrast_kd_factor: 2
aux_factor: 2
trans_cls_factor: 1
transfer_factor: 1

infonce_temp: 0.2
infonce_kd_temp: 0.2
kd_temp: 2
num_aug: 2

backbone_configs: 
  name: resnet32

network_configs:
  classifier_type: 'unified'
  proj_hidden_dim: 512
  proj_output_dim: 128
  init_from_last: false
  init_from_interpolation: true
  init_interpolation_factor: 0.95
  merge_attn: true

memory_configs:
  fixed_size: false
  memory_size: 2000

trainloader_params:
  batch_size: 128
  num_workers: 8
  drop_last: true

testloader_params:
  batch_size: 192
  num_workers: 8

init_optimizer_configs:
  name: sgd
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 5.e-4

init_scheduler_configs:
  name: multistep
  params:
    milestones: [60, 120, 170]
    gamma: 0.1

inc_optimizer_configs:
  name: sgd
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 2.e-4

inc_scheduler_configs:
  name: multistep
  params:
    milestones: [80, 120, 150]
    gamma: 0.1
